"""Added table for storing messages

Revision ID: 9503928c8ba8
Revises: 9aac8f1525d3
Create Date: 2024-04-03 17:22:46.268453

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9503928c8ba8"
down_revision: Union[str, None] = "9aac8f1525d3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "message",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("photo", sa.String(), nullable=True),
        sa.Column("sender", sa.Integer(), nullable=False),
        sa.Column("receiver", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("NOT(photo IS NULL AND text IS NULL)"),
        sa.ForeignKeyConstraint(
            ["receiver"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sender"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("message")
    # ### end Alembic commands ###
